export const draftPlayers = [
  {
    name: "Cam Ward",
    position: "QB",
    college: "Miami (FL)",
    nflTeam: "Tennessee Titans",
    overallRank: 1,
    positionRank: 1,
    overallPickNumber: 1,
    acquisitionMethod: "R1 • P1",
    drafted: false
  },
  {
    name: "Travis Hunter",
    position: "WR",
    college: "Colorado",
    nflTeam: "Jacksonville Jaguars",
    overallRank: 2,
    positionRank: 1,
    overallPickNumber: 2,
    acquisitionMethod: "R1 • P2",
    drafted: false
  },
  {
    name: "Ashton Jeanty",
    position: "RB",
    college: "Boise State",
    nflTeam: "Las Vegas Raiders",
    overallRank: 3,
    positionRank: 1,
    overallPickNumber: 6,
    acquisitionMethod: "R1 • P6",
    drafted: false
  },
  {
    name: "Tetairoa McMillan",
    position: "WR",
    college: "Arizona",
    nflTeam: "Carolina Panthers",
    overallRank: 4,
    positionRank: 2,
    overallPickNumber: 8,
    acquisitionMethod: "R1 • P8",
    drafted: false
  },
  {
    name: "Colston Loveland",
    position: "TE",
    college: "Michigan",
    nflTeam: "Chicago Bears",
    overallRank: 5,
    positionRank: 1,
    overallPickNumber: 10,
    acquisitionMethod: "R1 • P10",
    drafted: false
  },
  {
    name: "Tyler Warren",
    position: "TE",
    college: "Penn State",
    nflTeam: "Indianapolis Colts",
    overallRank: 6,
    positionRank: 2,
    overallPickNumber: 14,
    acquisitionMethod: "R1 • P14",
    drafted: false
  },
  {
    name: "Emeka Egbuka",
    position: "WR",
    college: "Ohio State",
    nflTeam: "Tampa Bay Buccaneers",
    overallRank: 7,
    positionRank: 3,
    overallPickNumber: 19,
    acquisitionMethod: "R1 • P19",
    drafted: false
  },
  {
    name: "Omarion Hampton",
    position: "RB",
    college: "North Carolina",
    nflTeam: "Los Angeles Chargers",
    overallRank: 8,
    positionRank: 2,
    overallPickNumber: 22,
    acquisitionMethod: "R1 • P22",
    drafted: false
  },
  {
    name: "Matthew Golden",
    position: "WR",
    college: "Texas",
    nflTeam: "Green Bay Packers",
    overallRank: 9,
    positionRank: 4,
    overallPickNumber: 23,
    acquisitionMethod: "R1 • P23",
    drafted: false
  },
  {
    name: "Jaxson Dart",
    position: "QB",
    college: "Ole Miss",
    nflTeam: "New York Giants",
    overallRank: 10,
    positionRank: 2,
    overallPickNumber: 25,
    acquisitionMethod: "R1 • P25",
    drafted: false
  },
  {
    name: "Jayden Higgins",
    position: "WR",
    college: "Iowa State",
    nflTeam: "Houston Texans",
    overallRank: 11,
    positionRank: 5,
    overallPickNumber: 34,
    acquisitionMethod: "R2 • P2",
    drafted: false
  },
  {
    name: "Quinshon Judkins",
    position: "RB",
    college: "Ohio State",
    nflTeam: "Cleveland Browns",
    overallRank: 12,
    positionRank: 3,
    overallPickNumber: 36,
    acquisitionMethod: "R2 • P4",
    drafted: false
  },
  {
    name: "TreVeyon Henderson",
    position: "RB",
    college: "Ohio State",
    nflTeam: "New England Patriots",
    overallRank: 13,
    positionRank: 4,
    overallPickNumber: 38,
    acquisitionMethod: "R2 • P6",
    drafted: false
  },
  {
    name: "Luther Burden III",
    position: "WR",
    college: "Missouri",
    nflTeam: "Chicago Bears",
    overallRank: 14,
    positionRank: 6,
    overallPickNumber: 39,
    acquisitionMethod: "R2 • P7",
    drafted: false
  },
  {
    name: "Tyler Shough",
    position: "QB",
    college: "Louisville",
    nflTeam: "New Orleans Saints",
    overallRank: 15,
    positionRank: 3,
    overallPickNumber: 40,
    acquisitionMethod: "R2 • P8",
    drafted: false
  },
  {
    name: "Mason Taylor",
    position: "TE",
    college: "LSU",
    nflTeam: "New York Jets",
    overallRank: 16,
    positionRank: 3,
    overallPickNumber: 42,
    acquisitionMethod: "R2 • P10",
    drafted: false
  },
  {
    name: "Terrance Ferguson",
    position: "TE",
    college: "Oregon",
    nflTeam: "Los Angeles Rams",
    overallRank: 17,
    positionRank: 4,
    overallPickNumber: 46,
    acquisitionMethod: "R2 • P14",
    drafted: false
  },
  {
    name: "Elijah Arroyo",
    position: "TE",
    college: "Miami (FL)",
    nflTeam: "Seattle Seahawks",
    overallRank: 18,
    positionRank: 5,
    overallPickNumber: 50,
    acquisitionMethod: "R2 • P18",
    drafted: false
  },
  {
    name: "Tre Harris",
    position: "WR",
    college: "Ole Miss",
    nflTeam: "Los Angeles Chargers",
    overallRank: 19,
    positionRank: 7,
    overallPickNumber: 55,
    acquisitionMethod: "R2 • P23",
    drafted: false
  },
  {
    name: "Jack Bech",
    position: "WR",
    college: "TCU",
    nflTeam: "Las Vegas Raiders",
    overallRank: 20,
    positionRank: 8,
    overallPickNumber: 58,
    acquisitionMethod: "R2 • P26",
    drafted: false
  },
  {
    name: "RJ Harvey",
    position: "RB",
    college: "UCF",
    nflTeam: "Denver Broncos",
    overallRank: 21,
    positionRank: 5,
    overallPickNumber: 60,
    acquisitionMethod: "R2 • P28",
    drafted: false
  },
  {
    name: "Harold Fannin",
    position: "TE",
    college: "Bowling Green",
    nflTeam: "Cleveland Browns",
    overallRank: 22,
    positionRank: 6,
    overallPickNumber: 67,
    acquisitionMethod: "R3 • P3",
    drafted: false
  },
  {
    name: "Kyle Williams",
    position: "WR",
    college: "Washington State",
    nflTeam: "New England Patriots",
    overallRank: 23,
    positionRank: 9,
    overallPickNumber: 69,
    acquisitionMethod: "R3 • P5",
    drafted: false
  },
  {
    name: "Isaac TeSlaa",
    position: "WR",
    college: "Arkansas",
    nflTeam: "Detroit Lions",
    overallRank: 24,
    positionRank: 10,
    overallPickNumber: 70,
    acquisitionMethod: "R3 • P6",
    drafted: false
  },
  {
    name: "Pat Bryant",
    position: "WR",
    college: "Illinois",
    nflTeam: "Denver Broncos",
    overallRank: 25,
    positionRank: 11,
    overallPickNumber: 74,
    acquisitionMethod: "R3 • P10",
    drafted: false
  },
  {
    name: "Jaylin Noel",
    position: "WR",
    college: "Iowa State",
    nflTeam: "Houston Texans",
    overallRank: 26,
    positionRank: 12,
    overallPickNumber: 79,
    acquisitionMethod: "R3 • P15",
    drafted: false
  },
  {
    name: "Kaleb Johnson",
    position: "RB",
    college: "Iowa",
    nflTeam: "Pittsburgh Steelers",
    overallRank: 27,
    positionRank: 6,
    overallPickNumber: 83,
    acquisitionMethod: "R3 • P19",
    drafted: false
  },
  {
    name: "Savion Williams",
    position: "WR",
    college: "TCU",
    nflTeam: "Green Bay Packers",
    overallRank: 28,
    positionRank: 13,
    overallPickNumber: 87,
    acquisitionMethod: "R3 • P23",
    drafted: false
  },
  {
    name: "Jalen Milroe",
    position: "QB",
    college: "Alabama",
    nflTeam: "Seattle Seahawks",
    overallRank: 29,
    positionRank: 4,
    overallPickNumber: 92,
    acquisitionMethod: "R3 • P28",
    drafted: false
  },
  {
    name: "Dillon Gabriel",
    position: "QB",
    college: "Oregon",
    nflTeam: "Cleveland Browns",
    overallRank: 30,
    positionRank: 5,
    overallPickNumber: 94,
    acquisitionMethod: "R3 • P30",
    drafted: false
  },
  {
    name: "Tai Felton",
    position: "WR",
    college: "Maryland",
    nflTeam: "Minnesota Vikings",
    overallRank: 31,
    positionRank: 14,
    overallPickNumber: 102,
    acquisitionMethod: "R3 • P38",
    drafted: false
  },
  {
    name: "Chimere Dike",
    position: "WR",
    college: "Florida",
    nflTeam: "Tennessee Titans",
    overallRank: 32,
    positionRank: 15,
    overallPickNumber: 103,
    acquisitionMethod: "R4 • P1",
    drafted: false
  },
  {
    name: "Bhayshul Tuten",
    position: "RB",
    college: "Virginia Tech",
    nflTeam: "Jacksonville Jaguars",
    overallRank: 33,
    positionRank: 7,
    overallPickNumber: 104,
    acquisitionMethod: "R4 • P2",
    drafted: false
  },
  {
    name: "Cam Skattebo",
    position: "RB",
    college: "Arizona State",
    nflTeam: "New York Giants",
    overallRank: 34,
    positionRank: 8,
    overallPickNumber: 105,
    acquisitionMethod: "R4 • P3",
    drafted: false
  },
  {
    name: "Dont'e Thornton",
    position: "WR",
    college: "Tennessee",
    nflTeam: "Las Vegas Raiders",
    overallRank: 35,
    positionRank: 16,
    overallPickNumber: 108,
    acquisitionMethod: "R4 • P6",
    drafted: false
  },
  {
    name: "Arian Smith",
    position: "WR",
    college: "Georgia",
    nflTeam: "New York Jets",
    overallRank: 36,
    positionRank: 17,
    overallPickNumber: 110,
    acquisitionMethod: "R4 • P8",
    drafted: false
  },
  {
    name: "Trevor Etienne",
    position: "RB",
    college: "Georgia",
    nflTeam: "Carolina Panthers",
    overallRank: 37,
    positionRank: 9,
    overallPickNumber: 114,
    acquisitionMethod: "R4 • P12",
    drafted: false
  },
  {
    name: "Woody Marks",
    position: "RB",
    college: "USC",
    nflTeam: "Houston Texans",
    overallRank: 38,
    positionRank: 10,
    overallPickNumber: 116,
    acquisitionMethod: "R4 • P14",
    drafted: false
  },
  {
    name: "Jarquez Hunter",
    position: "RB",
    college: "Auburn",
    nflTeam: "Los Angeles Rams",
    overallRank: 39,
    positionRank: 11,
    overallPickNumber: 117,
    acquisitionMethod: "R4 • P15",
    drafted: false
  },
  {
    name: "Gunnar Helm",
    position: "TE",
    college: "Texas",
    nflTeam: "Tennessee Titans",
    overallRank: 40,
    positionRank: 7,
    overallPickNumber: 120,
    acquisitionMethod: "R4 • P18",
    drafted: false
  },
  {
    name: "Dylan Sampson",
    position: "RB",
    college: "Tennessee",
    nflTeam: "Cleveland Browns",
    overallRank: 41,
    positionRank: 12,
    overallPickNumber: 126,
    acquisitionMethod: "R4 • P24",
    drafted: false
  },
  {
    name: "Jaylin Lane",
    position: "WR",
    college: "Virginia Tech",
    nflTeam: "Washington Commanders",
    overallRank: 42,
    positionRank: 18,
    overallPickNumber: 128,
    acquisitionMethod: "R4 • P26",
    drafted: false
  },
  {
    name: "Jalen Royals",
    position: "WR",
    college: "Utah State",
    nflTeam: "Kansas City Chiefs",
    overallRank: 43,
    positionRank: 19,
    overallPickNumber: 133,
    acquisitionMethod: "R4 • P31",
    drafted: false
  },
  {
    name: "Elic Ayomanor",
    position: "WR",
    college: "Stanford",
    nflTeam: "Tennessee Titans",
    overallRank: 44,
    positionRank: 20,
    overallPickNumber: 136,
    acquisitionMethod: "R4 • P34",
    drafted: false
  },
  {
    name: "Jordan Watkins",
    position: "WR",
    college: "Ole Miss",
    nflTeam: "San Francisco 49ers",
    overallRank: 45,
    positionRank: 21,
    overallPickNumber: 138,
    acquisitionMethod: "R4 • P36",
    drafted: false
  },
  {
    name: "Shedeur Sanders",
    position: "QB",
    college: "Colorado",
    nflTeam: "Cleveland Browns",
    overallRank: 46,
    positionRank: 6,
    overallPickNumber: 144,
    acquisitionMethod: "R5 • P6",
    drafted: false
  },
  {
    name: "Jordan James",
    position: "RB",
    college: "Oregon",
    nflTeam: "San Francisco 49ers",
    overallRank: 47,
    positionRank: 13,
    overallPickNumber: 147,
    acquisitionMethod: "R5 • P9",
    drafted: false
  },
  {
    name: "Jaydon Blue",
    position: "RB",
    college: "Texas",
    nflTeam: "Dallas Cowboys",
    overallRank: 48,
    positionRank: 14,
    overallPickNumber: 149,
    acquisitionMethod: "R5 • P11",
    drafted: false
  },
  {
    name: "DJ Giddens",
    position: "RB",
    college: "Kansas State",
    nflTeam: "Indianapolis Colts",
    overallRank: 49,
    positionRank: 15,
    overallPickNumber: 151,
    acquisitionMethod: "R5 • P13",
    drafted: false
  },
  {
    name: "KeAndre Lambert-Smith",
    position: "WR",
    college: "Auburn",
    nflTeam: "Los Angeles Chargers",
    overallRank: 50,
    positionRank: 22,
    overallPickNumber: 158,
    acquisitionMethod: "R5 • P20",
    drafted: false
  },
  {
    name: "Mitchell Evans",
    position: "TE",
    college: "Notre Dame",
    nflTeam: "Carolina Panthers",
    overallRank: 51,
    positionRank: 8,
    overallPickNumber: 163,
    acquisitionMethod: "R5 • P25",
    drafted: false
  },
  {
    name: "Oronde Gadsden II",
    position: "TE",
    college: "Syracuse",
    nflTeam: "Los Angeles Chargers",
    overallRank: 52,
    positionRank: 9,
    overallPickNumber: 165,
    acquisitionMethod: "R5 • P27",
    drafted: false
  },
  {
    name: "Tory Horton",
    position: "WR",
    college: "Colorado State",
    nflTeam: "Seattle Seahawks",
    overallRank: 53,
    positionRank: 23,
    overallPickNumber: 166,
    acquisitionMethod: "R5 • P28",
    drafted: false
  },
  {
    name: "Jackson Hawes",
    position: "TE",
    college: "Georgia Tech",
    nflTeam: "Buffalo Bills",
    overallRank: 54,
    positionRank: 10,
    overallPickNumber: 173,
    acquisitionMethod: "R5 • P35",
    drafted: false
  },
  {
    name: "Robbie Ouzts",
    position: "TE",
    college: "Alabama",
    nflTeam: "Seattle Seahawks",
    overallRank: 55,
    positionRank: 11,
    overallPickNumber: 175,
    acquisitionMethod: "R5 • P37",
    drafted: false
  },
  {
    name: "Ollie Gordon II",
    position: "RB",
    college: "Oklahoma State",
    nflTeam: "Miami Dolphins",
    overallRank: 56,
    positionRank: 16,
    overallPickNumber: 179,
    acquisitionMethod: "R6 • P3",
    drafted: false
  },
  {
    name: "Kyle McCord",
    position: "QB",
    college: "Syracuse",
    nflTeam: "Philadelphia Eagles",
    overallRank: 57,
    positionRank: 7,
    overallPickNumber: 181,
    acquisitionMethod: "R6 • P5",
    drafted: false
  },
  {
    name: "Andres Borregales",
    position: "K",
    college: "Miami (FL)",
    nflTeam: "New England Patriots",
    overallRank: 58,
    positionRank: 1,
    overallPickNumber: 182,
    acquisitionMethod: "R6 • P6",
    drafted: false
  },
  {
    name: "Devin Neal",
    position: "RB",
    college: "Kansas",
    nflTeam: "New Orleans Saints",
    overallRank: 59,
    positionRank: 17,
    overallPickNumber: 184,
    acquisitionMethod: "R6 • P8",
    drafted: false
  },
  {
    name: "Will Howard",
    position: "QB",
    college: "Ohio State",
    nflTeam: "Pittsburgh Steelers",
    overallRank: 60,
    positionRank: 8,
    overallPickNumber: 185,
    acquisitionMethod: "R6 • P9",
    drafted: false
  },
  {
    name: "Tyler Loop",
    position: "K",
    college: "Arizona",
    nflTeam: "Baltimore Ravens",
    overallRank: 61,
    positionRank: 2,
    overallPickNumber: 186,
    acquisitionMethod: "R6 • P10",
    drafted: false
  },
  {
    name: "Kalel Mullings",
    position: "RB",
    college: "Michigan",
    nflTeam: "Tennessee Titans",
    overallRank: 62,
    positionRank: 18,
    overallPickNumber: 188,
    acquisitionMethod: "R6 • P12",
    drafted: false
  },
  {
    name: "Riley Leonard",
    position: "QB",
    college: "Notre Dame",
    nflTeam: "Indianapolis Colts",
    overallRank: 63,
    positionRank: 9,
    overallPickNumber: 189,
    acquisitionMethod: "R6 • P13",
    drafted: false
  },
  {
    name: "Tahj Brooks",
    position: "RB",
    college: "Texas Tech",
    nflTeam: "Cincinnati Bengals",
    overallRank: 64,
    positionRank: 19,
    overallPickNumber: 193,
    acquisitionMethod: "R6 • P17",
    drafted: false
  },
  {
    name: "Graham Mertz",
    position: "QB",
    college: "Florida",
    nflTeam: "Houston Texans",
    overallRank: 65,
    positionRank: 10,
    overallPickNumber: 197,
    acquisitionMethod: "R6 • P21",
    drafted: false
  },
  {
    name: "Gavin Bartholomew",
    position: "TE",
    college: "Pittsburgh",
    nflTeam: "Minnesota Vikings",
    overallRank: 66,
    positionRank: 12,
    overallPickNumber: 202,
    acquisitionMethod: "R6 • P26",
    drafted: false
  },
  {
    name: "LaJohntay Wester",
    position: "WR",
    college: "Colorado",
    nflTeam: "Baltimore Ravens",
    overallRank: 67,
    positionRank: 24,
    overallPickNumber: 203,
    acquisitionMethod: "R6 • P27",
    drafted: false
  },
  {
    name: "Jimmy Horn",
    position: "WR",
    college: "Colorado",
    nflTeam: "Carolina Panthers",
    overallRank: 68,
    positionRank: 25,
    overallPickNumber: 208,
    acquisitionMethod: "R6 • P32",
    drafted: false
  },
  {
    name: "Tommy Mellott",
    position: "WR",
    college: "Montana State",
    nflTeam: "Las Vegas Raiders",
    overallRank: 69,
    positionRank: 26,
    overallPickNumber: 213,
    acquisitionMethod: "R6 • P37",
    drafted: false
  },
  {
    name: "Cam Miller",
    position: "QB",
    college: "North Dakota State",
    nflTeam: "Las Vegas Raiders",
    overallRank: 70,
    positionRank: 11,
    overallPickNumber: 215,
    acquisitionMethod: "R6 • P39",
    drafted: false
  },
  {
    name: "Thomas Fidone",
    position: "TE",
    college: "Nebraska",
    nflTeam: "New York Giants",
    overallRank: 71,
    positionRank: 13,
    overallPickNumber: 219,
    acquisitionMethod: "R7 • P3",
    drafted: false
  },
  {
    name: "Damien Martinez",
    position: "RB",
    college: "Miami (FL)",
    nflTeam: "Seattle Seahawks",
    overallRank: 72,
    positionRank: 20,
    overallPickNumber: 223,
    acquisitionMethod: "R7 • P7",
    drafted: false
  },
  {
    name: "Kurtis Rourke",
    position: "QB",
    college: "Indiana",
    nflTeam: "San Francisco 49ers",
    overallRank: 73,
    positionRank: 12,
    overallPickNumber: 227,
    acquisitionMethod: "R7 • P11",
    drafted: false
  },
  {
    name: "Brashard Smith",
    position: "RB",
    college: "SMU",
    nflTeam: "Kansas City Chiefs",
    overallRank: 74,
    positionRank: 21,
    overallPickNumber: 228,
    acquisitionMethod: "R7 • P12",
    drafted: false
  },
  {
    name: "Quinn Ewers",
    position: "QB",
    college: "Texas",
    nflTeam: "Miami Dolphins",
    overallRank: 75,
    positionRank: 13,
    overallPickNumber: 231,
    acquisitionMethod: "R7 • P15",
    drafted: false
  },
  {
    name: "Kyle Monangai",
    position: "RB",
    college: "Rutgers",
    nflTeam: "Chicago Bears",
    overallRank: 76,
    positionRank: 22,
    overallPickNumber: 233,
    acquisitionMethod: "R7 • P17",
    drafted: false
  },
  {
    name: "Tez Johnson",
    position: "WR",
    college: "Oregon",
    nflTeam: "Tampa Bay Buccaneers",
    overallRank: 77,
    positionRank: 27,
    overallPickNumber: 235,
    acquisitionMethod: "R7 • P19",
    drafted: false
  },
  {
    name: "LeQuint Allen",
    position: "RB",
    college: "Syracuse",
    nflTeam: "Jacksonville Jaguars",
    overallRank: 78,
    positionRank: 23,
    overallPickNumber: 236,
    acquisitionMethod: "R7 • P20",
    drafted: false
  },
  {
    name: "Ricky White III",
    position: "WR",
    college: "UNLV",
    nflTeam: "Seattle Seahawks",
    overallRank: 79,
    positionRank: 28,
    overallPickNumber: 238,
    acquisitionMethod: "R7 • P22",
    drafted: false
  },
  {
    name: "Phil Mafah",
    position: "RB",
    college: "Clemson",
    nflTeam: "Dallas Cowboys",
    overallRank: 80,
    positionRank: 24,
    overallPickNumber: 239,
    acquisitionMethod: "R7 • P23",
    drafted: false
  },
  {
    name: "Kaden Prather",
    position: "WR",
    college: "Maryland",
    nflTeam: "Buffalo Bills",
    overallRank: 81,
    positionRank: 29,
    overallPickNumber: 240,
    acquisitionMethod: "R7 • P24",
    drafted: false
  },
  {
    name: "Caleb Lohner",
    position: "TE",
    college: "Utah",
    nflTeam: "Denver Broncos",
    overallRank: 82,
    positionRank: 14,
    overallPickNumber: 241,
    acquisitionMethod: "R7 • P25",
    drafted: false
  },
  {
    name: "Konata Mumpfield",
    position: "WR",
    college: "Pittsburgh",
    nflTeam: "Los Angeles Rams",
    overallRank: 83,
    positionRank: 30,
    overallPickNumber: 242,
    acquisitionMethod: "R7 • P26",
    drafted: false
  },
  {
    name: "Dominic Lovett",
    position: "WR",
    college: "Georgia",
    nflTeam: "Detroit Lions",
    overallRank: 84,
    positionRank: 31,
    overallPickNumber: 244,
    acquisitionMethod: "R7 • P28",
    drafted: false
  },
  {
    name: "Jacory Croskey-Merritt",
    position: "RB",
    college: "Arizona",
    nflTeam: "Washington Commanders",
    overallRank: 85,
    positionRank: 25,
    overallPickNumber: 245,
    acquisitionMethod: "R7 • P29",
    drafted: false
  },
  {
    name: "Moliki Matavao",
    position: "TE",
    college: "UCLA",
    nflTeam: "New Orleans Saints",
    overallRank: 86,
    positionRank: 15,
    overallPickNumber: 248,
    acquisitionMethod: "R7 • P32",
    drafted: false
  },
  {
    name: "Junior Bergen",
    position: "WR",
    college: "Montana",
    nflTeam: "San Francisco 49ers",
    overallRank: 87,
    positionRank: 32,
    overallPickNumber: 252,
    acquisitionMethod: "R7 • P36",
    drafted: false
  },
  {
    name: "Luke Lachey",
    position: "TE",
    college: "Iowa",
    nflTeam: "Houston Texans",
    overallRank: 88,
    positionRank: 16,
    overallPickNumber: 255,
    acquisitionMethod: "R7 • P39",
    drafted: false
  },
  {
    name: "Philadelphia Eagles Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 89,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Houston Texans Defense ",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 90,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Minnesota Vikings Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 91,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Denver Broncos Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 92,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Baltimore Ravens Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 93,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Pittsburgh Steelers Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 94,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Kansas City Chiefs Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 95,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Buffalo Bills Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 96,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Detroit Lions Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 97,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Dallas Cowboys Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 98,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Los Angeles Rams Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 99,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Washington Commanders Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 100,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "San Francisco 49ers Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 101,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Miami Dolphins Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 102,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Green Bay Packers Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 103,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Seattle Seahawks Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 104,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Tampa Bay Buccaneers Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 105,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Indianapolis Colts Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 106,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Cleveland Browns Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 107,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Cincinnati Bengals Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 108,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Chicago Bears Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 109,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Arizona Cardinals Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 110,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Los Angeles Chargers Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 111,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "New York Jets Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 112,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Atlanta Falcons Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 113,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "New Orleans Saints Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 114,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Las Vegas Raiders Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 115,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "New England Patriots Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 116,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Jacksonville Jaguars Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 117,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Carolina Panthers Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 118,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "New York Giants Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 119,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
  {
    name: "Tennessee Titans Defense",
    position: "DEF",
    college: "nan",
    nflTeam: "nan",
    overallRank: 120,
    positionRank: null,
    overallPickNumber: null,
    acquisitionMethod: null,
    drafted: false
  },
];