// src/data/teams.js

export const teams = [
    {
      id: 1,
      name: "Belltown Raptors",
      abbrev: "BEL",
      owner: "Jason",
      logo: "https://i.postimg.cc/6pS5VRqQ/Belltown-Raptors-logo.png",
      colors: ["#753bbd", "#ba0c2f", "#8a8d8f"],
    },
    {
      id: 2,
      name: "Belleview Badgers",
      abbrev: "FGH",
      owner: "Patrick",
      logo: "https://i.postimg.cc/0NSHwkHL/Belleview-Badgers-Primary-Logo.png",
      colors: ["#006747", "#1E3952", "#F2F7F9"],
    },
    {
      id: 3,
      name: "Mt. Lebanon Cake Eaters",
      abbrev: "MTL",
      owner: "Michael M",
      logo: "https://i.postimg.cc/rmWmw914/Cake-Eaters-Logo-jpg.jpg",
      colors: ["#023351", "#DCAC24", null],
    },
    {
      id: 4,
      name: "Double Trouble",
      abbrev: "DBT",
      owner: "Noah / Shane",
      logo: "https://i.postimg.cc/PqPy9Gd4/Double-Trouble-logo.png",
      colors: ["#120a11", "#351b4b", "#ca5517"],
    },
    {
      id: 5,
      name: "The Lone Ginger",
      abbrev: "TLG",
      owner: "Ginger",
      logo: "https://i.postimg.cc/bNtyRdXY/Lone-Ginger-Logo.png",
      colors: ["#d56920", "#13110d", "#4b775b"],
    },
    {
      id: 6,
      name: "Minshew's Maniacs",
      abbrev: "MIN",
      owner: "Matt S",
      logo: "https://i.postimg.cc/zvNpv0gH/Minshew-s-Maniacs-Logo.png",
      colors: ["#A60F2D", "#4D4D4D", null],
    },
    {
      id: 7,
      name: "Red Pandas",
      abbrev: "RDP",
      owner: "Matt M",
      logo: "https://i.postimg.cc/4dV6Pn6T/Red-Pandas-Primary-Logo-draft.png",
      colors: ["#c90a00", "#797574", "#38c4f6"],
    },
    {
      id: 8,
      name: "Elemental Heroes",
      abbrev: "ELH",
      owner: "Joseph",
      logo: "https://i.postimg.cc/9z5BK1WQ/Elemental-Heroes-Logo.png",
      colors: ["#83e1a2", "#fd6e6e", "#7799c9"],
    },
    {
      id: 9,
      name: "bop pop",
      abbrev: "BOP",
      owner: "Jack",
      logo: "https://i.postimg.cc/4xhnSwrc/bop-pop-logo.png",
      colors: ["#fedb35", "#f88618", null],
    },
    {
      id: 10,
      name: "BeerNeverBrokeMyHeart",
      abbrev: "BNB",
      owner: "Michael B",
      logo: "https://i.postimg.cc/B634ZfMT/Beer-Never-Broke-My-Heart-Logo.png",
      colors: ["#0E1A27", "#F4E3C3", "#B53329"],
    },
    {
      id: 11,
      name: "Bimg Bamg Boomg",
      abbrev: "BBB",
      owner: "Alex",
      logo: "https://i.postimg.cc/L6PTMdg4/Bimg-Bamg-Boomg-Logo.png",
      colors: ["#712D7C", "#9BC46D", "#9E9E9E"],
    },
    {
      id: 12,
      name: "Detroit Dawgs",
      abbrev: "DET",
      owner: "Conor",
      logo: "https://i.postimg.cc/X76Vv3hr/Detroit-Dawgs-Logo.png",
      colors: ["#5a341f", "#da2127", "#f3bd37"],
    },
  ];